# Generated by Django 5.0.4 on 2024-04-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beatbuddy', '0004_song_trending'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='favourite',
            field=models.BooleanField(default=False, help_text='0-show,1-Hidden'),
        ),
    ]
